modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/xgs-storymode-items-and-more"
logoFile="icon.png"
authors="Xg787"
description='''A Mod that adds Story Mode Items, Armor and More'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[accessTransformers]]
    file="accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sectioned_creative_tab_lib"
    type="required"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
